version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: sqlite
    volumes:
      - sqlite_data:/var/lib/sqlite

volumes:
  sqlite_data:
